# Generated by Django 5.2.5 on 2025-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo da clínica que aparecerá no navbar', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Configuração da Clínica',
            },
        ),
    ]
