# Generated by Django 5.2.5 on 2025-08-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativa',
            name='categoria',
            field=models.CharField(choices=[('BOASVINDAS', 'Boas vindas'), ('TRATAMENTO', 'Tratamento'), ('ACOMPANHAMENTO', 'Acompanhamento'), ('REVISÃO', 'Revisão'), ('ENCERRAMENTO', 'Encerramento'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
