# Generated by Django 5.2.5 on 2025-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cena',
            name='conteudo_textual',
            field=models.TextField(blank=True, help_text='Texto principal que aparecerá na cena.', null=True),
        ),
        migrations.AddField(
            model_name='cena',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de apoio para a cena.', null=True, upload_to='imagem_cenas'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='titulo',
            field=models.CharField(help_text="Título interno para identificar a cena (ex: 'Cena de Boas Vindas')", max_length=100),
        ),
        migrations.AlterField(
            model_name='cena',
            name='video',
            field=models.URLField(blank=True, help_text='Link do vídeo para a cena (opcional).', null=True),
        ),
    ]
