# Generated by Django 5.2.5 on 2026-03-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='narrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cenas', to='narrativa.narrativa'),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='narrativa.categoria'),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='narrativa.clinica'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_associada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='narrativa.cena'),
        ),
    ]
