# Generated by Django 5.2.5 on 2025-09-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0002_alter_narrativa_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('narrativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cena', to='narrativa.narrativa')),
            ],
        ),
    ]
