# Generated by Django 5.2.5 on 2026-01-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0002_configuracaoclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Identificador na URL (ex: clinica-pax)', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('assinatura_ativa', models.BooleanField(default=False)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoClinica',
        ),
        migrations.AlterModelOptions(
            name='logvisitacena',
            options={},
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin_clinica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cena',
            name='conteudo_textual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cena',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagem_cenas'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cena',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logvisitacena',
            name='cena_visitada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='logvisitacena',
            name='narrativa_associada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='narrativa.narrativa'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha (uma)'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha (várias)'), ('ESCALA_5', 'Escala 1 a 5')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_de_origem', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='categoria',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='narrativa.clinica'),
        ),
        migrations.AddField(
            model_name='narrativa',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrativas', to='narrativa.clinica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='narrativa.clinica'),
        ),
    ]
