# Generated by Django 5.2.5 on 2026-03-28 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0002_alter_cena_narrativa_alter_narrativa_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='narrativa',
            field=models.ForeignKey(blank=True, help_text='Lembrete: Não esqueça de vincular esta cena a uma narrativa depois para que ela seja exibida aos pacientes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cenas', to='narrativa.narrativa'),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Opcional. Você pode criar apenas com imagens se preferir.', null=True),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='thumb',
            field=models.ImageField(blank=True, help_text='Opcional. Você pode adicionar a imagem de capa depois.', null=True, upload_to='capas/'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_associada',
            field=models.OneToOneField(blank=True, help_text='Lembrete: Não esqueça de vincular este questionário a uma cena depois para que ele seja exibido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='narrativa.cena'),
        ),
    ]
