# Generated by Django 5.2.5 on 2025-09-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0002_cena_conteudo_textual_cena_imagem_alter_cena_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_da_opcao', models.CharField(max_length=255)),
                ('cena_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cenas_de_destino', to='narrativa.cena')),
                ('cena_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolhas', to='narrativa.cena')),
            ],
        ),
    ]
