# Generated by Django 5.2.5 on 2026-02-19 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0003_clinica_delete_configuracaoclinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcaoresposta',
            name='pergunta',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clinica',
            options={},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cena',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='logvisitacena',
            old_name='timestamp',
            new_name='data_visita',
        ),
        migrations.RenameField(
            model_name='sessaopaciente',
            old_name='data_criacao',
            new_name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='conteudo_textual',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='data_expiracao',
        ),
        migrations.RemoveField(
            model_name='narrativa',
            name='cena_inicial',
        ),
        migrations.RemoveField(
            model_name='narrativa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='narrativa',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='texto_pergunta',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='tipo_resposta',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='data_resposta',
        ),
        migrations.AddField(
            model_name='cena',
            name='conteudo',
            field=models.TextField(default='Conteúdo inicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cena',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinica',
            name='limite_narrativas',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='clinica',
            name='limite_respostas_mes',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='clinica',
            name='plano',
            field=models.CharField(choices=[('BASIC', 'Básico'), ('PRO', 'Profissional'), ('ADVANCED', 'Avançado'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativa',
            name='capa',
            field=models.ImageField(default='', upload_to='capas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(default='Pergunta padrão', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha')], default='TEXTO', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cena',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cenas/'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='logvisitacena',
            name='narrativa_associada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='narrativa.narrativa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logvisitacena',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='narrativa.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='narrativa.clinica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_associada',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionario', to='narrativa.cena'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino_de', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narrativa.pergunta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sessaopaciente',
            name='narrativa_perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='narrativa.narrativa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessaopaciente',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrativa.clinica'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='narrativas_vistas',
            field=models.ManyToManyField(to='narrativa.narrativa'),
        ),
        migrations.DeleteModel(
            name='Escolha',
        ),
        migrations.DeleteModel(
            name='OpcaoResposta',
        ),
    ]
