# Generated by Django 5.2.5 on 2025-09-21 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0003_escolha'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativa',
            name='cena_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='narrativa.cena'),
        ),
    ]
