# Generated by Django 5.2.5 on 2026-03-28 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('narrativa', '0003_alter_cena_narrativa_alter_narrativa_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(default='Geral', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='narrativa',
            name='cena_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='narrativa.cena'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='cena_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_de_origem', to='narrativa.cena'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='data_resposta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='narrativas_vistas',
            field=models.ManyToManyField(blank=True, to='narrativa.narrativa'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='conteudo_textual',
            field=models.TextField(blank=True, help_text='Texto principal da cena.', null=True),
        ),
        migrations.AlterField(
            model_name='cena',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de apoio.', null=True, upload_to='imagem_cenas'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='narrativa',
            field=models.ForeignKey(blank=True, help_text='Lembrete: Vincule a uma narrativa para exibi-la.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cenas', to='narrativa.narrativa'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='titulo',
            field=models.CharField(help_text='Título interno para identificar a cena', max_length=100),
        ),
        migrations.AlterField(
            model_name='cena',
            name='video',
            field=models.URLField(blank=True, help_text='Link do vídeo (opcional).', null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da clínica. Recomendado: 250x45 px.', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='escolha',
            name='cena_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cenas_de_destino', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrativa.categoria'),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Opcional.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='thumb',
            field=models.ImageField(blank=True, help_text='Opcional. Imagem de capa.', null=True, upload_to='thumb_narrativas'),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto_pergunta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha (apenas uma resposta)'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha (várias respostas)'), ('ESCALA_5', 'Escala de Satisfação (1 a 5)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_associada',
            field=models.ForeignKey(blank=True, help_text='Lembrete: Vincule a uma cena.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='titulo',
            field=models.CharField(help_text='Título do questionário.', max_length=200),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='narrativa.pergunta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='session_key',
            field=models.CharField(help_text='ID da sessão do paciente', max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='LogVisitaCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cena_visitada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='narrativa.cena')),
                ('narrativa_associada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_visita', to='narrativa.narrativa')),
            ],
            options={
                'ordering': ['session_key', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessaoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('narrativa_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrativa.narrativa')),
            ],
        ),
    ]
