# Generated by Django 5.2.5 on 2025-09-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0004_narrativa_cena_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='narrativas_vistas',
            field=models.ManyToManyField(blank=True, to='narrativa.narrativa'),
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título do questionário (ex: 'Pesquisa de Satisfação')", max_length=200)),
                ('cena_associada', models.ForeignKey(blank=True, help_text='Opcional: cena ao final da qual este questionário será exibido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios', to='narrativa.cena')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=500)),
                ('tipo_resposta', models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha (apenas uma resposta)'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha (várias respostas)'), ('ESCALA_5', 'Escala de Satisfação (1 a 5)')], max_length=20)),
                ('opcoes_resposta', models.TextField(blank=True, help_text="Para 'Múltipla Escolha' ou 'Escala', separe as opções por vírgula (ex: 'Ruim,Regular,Bom').", null=True)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='narrativa.questionario')),
            ],
        ),
    ]
