# Generated by Django 5.2.5 on 2026-02-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('narrativa', '0004_remove_opcaoresposta_pergunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_custom_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='narrativas_vistas',
            field=models.ManyToManyField(blank=True, to='narrativa.narrativa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_custom_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
