# Generated by Django 5.2.5 on 2026-04-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0004_alter_categoria_options_remove_categoria_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='nome_exibicao',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='pid',
        ),
        migrations.AddField(
            model_name='plano',
            name='descricao_curta',
            field=models.CharField(default='Ideal para acompanhamento de pacientes', help_text='Aparece abaixo do nome na tela de vendas.', max_length=200),
        ),
        migrations.AddField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False, help_text="Marque para deixar este plano com visual de 'Recomendado' na tela."),
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_pacientes',
            field=models.IntegerField(default=5, help_text='Quantos pacientes a clínica pode cadastrar?'),
        ),
        migrations.AddField(
            model_name='plano',
            name='stripe_price_id',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_narrativas',
            field=models.IntegerField(default=1, help_text='Quantas narrativas ativas a clínica pode ter simultaneamente?'),
        ),
    ]
