# Generated by Django 5.2.5 on 2025-09-24 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0005_alter_usuario_narrativas_vistas_questionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='ID da sessão do paciente anônimo', max_length=40)),
                ('texto_resposta', models.TextField()),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='narrativa.pergunta')),
            ],
        ),
    ]
