# Generated by Django 5.2.5 on 2026-05-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0005_rename_nome_exibicao_plano_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo global do sistema (se aplicável)', null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail usado no checkout do Stripe', max_length=254, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False, help_text='Marca como True após o usuário criar a conta.')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narrativa.plano')),
            ],
        ),
    ]
