# Generated by Django 5.2.5 on 2026-03-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('narrativa', '0005_alter_usuario_groups_alter_usuario_narrativas_vistas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('pid', models.CharField(help_text='ID do Preço no Stripe', max_length=255)),
                ('limite_narrativas', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='sessaopaciente',
            name='narrativa_perfil',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='limite_narrativas',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='limite_respostas_mes',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='narrativa',
            name='visualizacoes',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='cena_destino',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='narrativas_vistas',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_custom_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_custom_permissions_set', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='plano_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrativa.plano'),
        ),
        migrations.DeleteModel(
            name='LogVisitaCena',
        ),
        migrations.DeleteModel(
            name='SessaoPaciente',
        ),
    ]
