# Generated by Django 5.2.5 on 2026-05-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0006_configuracaoclinica_pagamentopendente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentopendente',
            options={'verbose_name': 'Pagamento Pendente', 'verbose_name_plural': 'Pagamentos Pendentes'},
        ),
    ]
