# Generated by Django 5.2.5 on 2025-10-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0006_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Casal Hétero, Casal Homossexual, Gestante, etc.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessaoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrativa.perfil')),
            ],
        ),
    ]
