# Generated by Django 5.2.5 on 2026-05-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0007_alter_pagamentopendente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='conteudo_textual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cena',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagem_cenas'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='narrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cenas', to='narrativa.narrativa'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cena',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='configuracaoclinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumb_narrativas'),
        ),
        migrations.AlterField(
            model_name='pagamentopendente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamentopendente',
            name='utilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha'), ('MULTIPLA_ESCOLHA', 'Múltipla Múltipla'), ('ESCALA_5', 'Escala (1-5)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plano',
            name='descricao_curta',
            field=models.CharField(default='Ideal para acompanhamento de pacientes', max_length=200),
        ),
        migrations.AlterField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_narrativas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_pacientes',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
