# Generated by Django 5.2.5 on 2025-10-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0007_perfil_sessaopaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaopaciente',
            name='perfil',
        ),
        migrations.AddField(
            model_name='sessaopaciente',
            name='narrativa_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrativa.narrativa'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
