# Generated by Django 5.2.5 on 2025-10-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0008_remove_sessaopaciente_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='cena_destino',
            field=models.ForeignKey(blank=True, help_text='Opcional: para qual cena o paciente deve ser levado após responder este questionário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_de_origem', to='narrativa.cena'),
        ),
    ]
