# Generated by Django 5.2.5 on 2025-10-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0009_questionario_cena_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='cena_destino',
        ),
    ]
