# Generated by Django 5.2.5 on 2025-10-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0010_remove_questionario_cena_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='opcoes_resposta',
        ),
        migrations.AddField(
            model_name='questionario',
            name='cena_destino',
            field=models.ForeignKey(blank=True, help_text='Opcional: para qual cena o paciente deve ser levado após responder este questionário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_de_origem', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha (apenas uma resposta)'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha (várias respostas)'), ('ESCALA_5', 'Escala de Satisfação (1 a 5)'), ('LISTA_SUSPENSA', 'Lista Suspensa (Dropdown)')], max_length=20),
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='narrativa.pergunta')),
            ],
        ),
    ]
