# Generated by Django 5.2.5 on 2025-10-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0011_remove_pergunta_opcoes_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha (apenas uma resposta)'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha (várias respostas)'), ('ESCALA_5', 'Escala de Satisfação (1 a 5)')], max_length=20),
        ),
    ]
