# Generated by Django 5.2.5 on 2025-10-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0012_alter_pergunta_tipo_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='cena_destino',
        ),
    ]
