# Generated by Django 5.2.5 on 2025-10-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0013_remove_questionario_cena_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='cena_destino',
            field=models.ForeignKey(blank=True, help_text='Opcional: para qual cena o paciente deve ser levado após responder este questionário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_de_origem', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha (apenas uma resposta)'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha (várias respostas)'), ('ESCALA_5', 'Escala de Satisfação (1 a 5)'), ('LISTA_SUSPENSA', 'Lista Suspensa (Dropdown)')], max_length=20),
        ),
    ]
