# Generated by Django 5.2.5 on 2025-10-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0014_questionario_cena_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='conteudo_textual',
            field=models.TextField(blank=True, help_text='Texto principal da cena.', null=True),
        ),
        migrations.AlterField(
            model_name='cena',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de apoio.', null=True, upload_to='imagem_cenas'),
        ),
        migrations.AlterField(
            model_name='cena',
            name='titulo',
            field=models.CharField(help_text='Título interno para identificar a cena', max_length=100),
        ),
        migrations.AlterField(
            model_name='cena',
            name='video',
            field=models.URLField(blank=True, help_text='Link do vídeo (opcional).', null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=models.CharField(choices=[('TEXTO', 'Texto Livre'), ('UNICA_ESCOLHA', 'Múltipla Escolha (apenas uma resposta)'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha (várias respostas)'), ('ESCALA_5', 'Escala de Satisfação (1 a 5)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_associada',
            field=models.ForeignKey(blank=True, help_text='Cena ao final da qual este questionário será exibido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cena_destino',
            field=models.ForeignKey(blank=True, help_text='Para qual cena o paciente deve ir após responder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_de_origem', to='narrativa.cena'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='titulo',
            field=models.CharField(help_text='Título do questionário.', max_length=200),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='session_key',
            field=models.CharField(help_text='ID da sessão do paciente', max_length=40),
        ),
    ]
