# Generated by Django 5.2.5 on 2025-10-22 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0015_alter_cena_conteudo_textual_alter_cena_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogVisitaCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cena_visitada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='narrativa.cena')),
                ('narrativa_associada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_visita', to='narrativa.narrativa')),
            ],
            options={
                'ordering': ['session_key', 'timestamp'],
            },
        ),
    ]
