# Generated by Django 5.2.5 on 2025-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0016_logvisitacena'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração Principal', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Faça o upload do logo da clínica aqui.', null=True, upload_to='logo_clinica/')),
            ],
            options={
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
