# Generated by Django 5.2.5 on 2025-11-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0017_configuracaoclinica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoClinica',
        ),
    ]
